### ISSUE TITLE
demo.ipynb import issues

### ISSUE THREAD

**Issue by IdoWSC** [akosiorek/hart#4]
Hi,
I have a problem running the demo:
ImportError                               Traceback (most recent call last)
<ipython-input-1-489311711474> in <module>()
      7 
      8 from hart.data import disp
----> 9 from hart.data.kitti.tools import get_data
     10 from hart.model import util
     11 from hart.model.attention_ops import FixedStdAttention

C:\Program Files\Anaconda3\Lib\site-packages\hart\hart\data\kitti\tools.py in <module>()
     26 import tensorflow as tf
     27 
---> 28 import neurocity as nct
     29 from neurocity.data import store
     30 from neurocity.data import tools as data_tools

C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\__init__.py in <module>()
     20 ########################################################################################
     21 
---> 22 from component.model.base import train_mode, test_mode, mode
     23 from component import loss, layer
     24 from component.model.model import Model

C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\component\__init__.py in <module>()
     23 
     24 import tensorflow as tf
---> 25 from layer import Layer
     26 from model.model import Model
     27 

C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\component\layer.py in <module>()
     26 import numpy as np
     27 
---> 28 from neurocity.component.model import base
     29 
     30 

C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\component\__init__.py in <module>()
     23 
     24 import tensorflow as tf
---> 25 from layer import Layer
     26 from model.model import Model
     27 

ImportError: cannot import name 'Layer'

**Comment by akosiorek** [comment]
The class `Layer` is defined in `neurocity.component.layer` (at https://github.com/akosiorek/hart/blob/master/neurocity/component/layer.py)  I assume the error has to do with how environment variables are set on your system. Can you try adding the hart folder to your PYTHONPATH?

**Comment by IdoWSC** [comment]
Thx Adam,
I have hart, neurocity, and component all added to PYTHONPATH. I also check
layer.py and saw that in fact Layer is defined there. I'll need to check
why does this problem occur.

By the way, has the script ever run on Windows and/or Python3+?

**Comment by akosiorek** [comment]
> I have hart, neurocity, and component all added to PYTHONPATH

I have only hart in my PYTHONPATH; that might be the issue.

> By the way, has the script ever run on Windows and/or Python3+?

I tested only on MacOS and Linux and Python 2.7

**Comment by IdoWSC** [comment]
I think I found the source of the issue.
 File "C:\Program Files\Anaconda3\Lib\site-packages\hart\hart\model\attention_ops.py", line 28, in <module>
    from hart.model import tensor_ops
  File "C:\Program Files\Anaconda3\Lib\site-packages\hart\hart\model\tensor_ops.py", line 23, in <module>
    from neurocity.tensor_ops import broadcast_against
  File "C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\__init__.py", line 22, in <module>
    from component.model.base import train_mode, test_mode, mode
  File "C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\component\__init__.py", line 25, in <module>
    from layer import Layer
  File "C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\component\layer.py", line 28, in <module>
    from neurocity.component.model import base
  File "C:\Program Files\Anaconda3\Lib\site-packages\hart\neurocity\component\__init__.py", line 25, in <module>
    from layer import Layer
ImportError: cannot import name 'Layer'

in hart\neurocity\__init__.py there is an import from component.model.base which first runs component/__init__.py.

There there is an import from layer which runs component/model/__init__.py that calls for import from component.model.model base that is importing layer again that eventually imports base again and so on.

this infinite loop is whats causing this failure

**Comment by IdoWSC** [comment]
The source for the issue when using Python3.3+ can be found here:
[import_traps](http://ncoghlan-devs-python-notes.readthedocs.io/en/latest/python_concepts/import_traps.html)

**Comment by IdoWSC** [comment]
I have modified your package to comply with py3.3+ and tf1.3+ if it interests you guys contact me

**Comment by akosiorek** [comment]
Good job @IdoWSC. Sure, it'd be great to have. Would you like to submit a PR?

**Comment by IdoWSC** [comment]
Submitted a pull request

**Comment by ghost** [comment]
I run demo.ipynb,but I do not found result picture.

**Comment by ghost** [comment]
why not use plt.show()? I can not to show the picture.
