### ISSUE TITLE
ImportError: No module named 'component'?

### ISSUE THREAD

**Issue by chenfsjz** [akosiorek/hart#8]
Hi! when I ready to run train_hart_kitti.py script, there is a wrong msg "No module named 'component' 
".The whole code is as below:

    Traceback (most recent call last):
    File "../hart/scripts/train_hart_kitti.py", line 34, in <module>
    from hart.data.kitti.tools import get_data
    File "../hart/scripts/../hart/data/kitti/tools.py", line 28, in <module>
    import neurocity as nct
    File "../hart/scripts/../neurocity/__init__.py", line 22, in <module>
    from component.model.base import train_mode,test_mode,mode
    ImportError: No module named 'component'

**Comment by akosiorek** [comment]
Hi @chenfsjz; the module `component` is located in hart/neurocity. Could you try to add hart/neurocity to your PYTHONPATH? This should solve the problem.

Also, you should invoke the training script from the hart directory by executing ` python scripts/train_hart_kitti.py`.
